# Generated by Django 5.1.6 on 2025-03-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('user_email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('user_passwd', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50)),
                ('user_otp', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='website_details',
            fields=[
                ('website_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_name', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.JSONField(default=dict)),
                ('product_ratings', models.JSONField(default=dict)),
                ('currency', models.CharField(max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('product_url', models.URLField()),
                ('product_image_url', models.JSONField(default=dict, null=True)),
                ('product_details', models.JSONField(null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.categories')),
                ('website_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.website_details')),
            ],
        ),
        migrations.CreateModel(
            name='price_track',
            fields=[
                ('track_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desired_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tracking_status', models.CharField(choices=[('1', 'Active'), ('2', 'Completed'), ('3', 'Cancelled')], default='Active', max_length=10)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.categories')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='user_request',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.categories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='request_result',
            fields=[
                ('result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.products')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_request')),
            ],
        ),
    ]
