# Generated by Django 5.1.6 on 2025-03-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_passwd', models.CharField(max_length=20)),
                ('user_otp', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
