# Generated by Django 5.1.6 on 2025-03-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='created_at',
        ),
        migrations.AddField(
            model_name='products',
            name='product_details',
            field=models.JSONField(null=True),
        ),
    ]
