# Generated by Django 5.1.6 on 2025-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_url',
            field=models.URLField(max_length=800),
        ),
    ]
