# Generated by Django 4.2.18 on 2025-04-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_track',
            name='tracking_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Completed')], default='1', max_length=10),
        ),
    ]
