# Generated by Django 4.2.18 on 2025-04-10 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_price_track_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
