# Generated by Django 5.1.6 on 2025-04-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_socialaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socialaccount',
        ),
    ]
